# Generated by Django 5.2.4 on 2025-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_product_discount_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
