# Generated by Django 5.2.4 on 2025-08-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_blog_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="archived",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="apps.blogcategory",
            ),
        ),
    ]
