# Generated by Django 5.2.4 on 2025-08-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="charfield",
        ),
        migrations.AddField(
            model_name="group",
            name="bigintfield",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="binaryfield",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="booleanfield",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="datefield",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="datetimefield",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="decimalfield",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="durationfield",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="emailfield",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="filefield",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="group",
            name="filepathfield",
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="floatfield",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="genericipfield",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="imagefield",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="group",
            name="integerfield",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="jsonfield",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="positivebigintegerfield",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="positiveintegerfield",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="positivesmallintegerfield",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="textfield",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="timefield",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[("vip", "VIP"), ("standard", "Standard")],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="urlfield",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="uuidfield",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
