# Generated by Django 5.2.4 on 2025-08-09 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_rename_name_group_charfield_group_bigintfield_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="filepathfield",
        ),
    ]
