# Generated by Django 5.2.4 on 2025-08-16 05:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_blog_archived_alter_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
