# Generated by Django 5.2.4 on 2025-08-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_remove_group_filepathfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audio", [("vinyl", "Vinyl"), ("cd", "CD")]),
                    ("Video", [("vhs", "VHS Tape"), ("dvd", "DVD")]),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
    ]
