# Generated by Django 5.2.4 on 2025-08-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_blog_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Maqola", "verbose_name_plural": "Maqolalar"},
        ),
        migrations.AddField(
            model_name="blog",
            name="is_premium",
            field=models.BooleanField(db_default=False),
        ),
    ]
