# Generated by Django 5.2.4 on 2025-08-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_alter_blog_options_blog_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="price",
            field=models.IntegerField(db_default=1500),
        ),
    ]
