# Generated by Django 5.2.4 on 2025-08-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_alter_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slugfield",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
